project_name: frodobot-gnm-lelan
run_name: frodobot-gnm
SACSoN: False
keep_learning: True

#repo_id: frodobots_dataset
#root: /media/noriaki/Noriaki_Data3
repo_id: frodobots_dataset
root: /nfs/kun2/datasets/frodobots_v1_export
episode-index: 0

late_fusion: False

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 350
eval_batch_size: 100

epochs: 200
gpu_ids: [0]
num_workers: 12
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 6
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

#
10k_data: False
# model params
model_type: il_exaug_gps_map2_lan
obs_encoding_size: 1024
goal_encoding_size: 1024
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]
clip_type: "ViT-B/32"

# diffusion model params
num_diffusion_iters: 10

# FrodoBot dataset ratio
ratio_f: 0.9
horizon_short: 20
horizon_long: 100

# mask 
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5 # 5
#alpha: 1e-4
alpha: 0.5

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: True

# dataset specific parameters
image_size: [96, 96] # width, height
image_size_clip: [224, 224] # width, height

ft_frod: False
aug_shadow: True
bdd: True

datasets:
  frodobot:
    train: 11434305
    test: 11434305
    negative_mining: True

datasets_bdd:    
  train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/bdd/train/
  test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/bdd/test/
  #image: /media/noriaki/Noriaki_Data2/BDD_dataset/samples-1k_dataset
  image: /nfs/kun2/datasets/bdd100k/BDD_imgs
  backside: False
  aug_seq: False
  only_front: True
  waypoint_spacing: 0.12   

#datasets_ft:    
#  frodobot_ft:
#    train: /media/noriaki/Noriaki_Data/dataset/frodobot_ft/train/
#    test: /media/noriaki/Noriaki_Data/dataset/frodobot_ft/test/
#    image: /media/noriaki/Noriaki_Data2/frodobot_ft/
#    pickle: /media/noriaki/Noriaki_Data2/frodobot_ft/
#    backside: False
#    aug_seq: False
#    only_front: True
#    waypoint_spacing: 0.12    
    
datasets_sub:
  recon:
    data_folder: /nfs/kun2/datasets/gnm_dataset/recon
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/recon/train/ # path to train folder with traj_names.txt
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/recon/test/ # path to test folder with traj_names.txt
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1 # how many goals are sampled per observation
    negative_mining: True # negative mining from the ViNG paper (Shah et al.)
  go_stanford:
    data_folder: /nfs/kun2/datasets/gnm_dataset/go_stanford_cropped # datasets/stanford_go_new
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/go_stanford/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/go_stanford/test/
    end_slack: 0
    goals_per_obs: 2 # increase dataset size
    negative_mining: True
  cory_hall:
    data_folder: /nfs/kun2/datasets/gnm_dataset/cory_hall
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/cory_hall/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/cory_hall/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  tartan_drive:
    data_folder: /nfs/kun2/datasets/gnm_dataset/tartan_drive
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/tartan_drive/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/tartan_drive/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  sacson:
    data_folder: /nfs/kun2/datasets/gnm_dataset/sacson
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/sacson/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/sacson/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  seattle:
    data_folder: /nfs/kun2/datasets/gnm_dataset/seattle/
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/seattle/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/seattle/test/
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True
  scand:
    data_folder: /nfs/kun2/datasets/gnm_dataset/scand/
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/scand/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/scand/test/
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True
    

datasets_lan:  
  go_stanford4:
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_gs4/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_gs4/test/
    image: /nfs/kun2/datasets/lelan/dataset_LeLaN_gs4/image/
    pickle: /nfs/kun2/datasets/lelan/dataset_LeLaN_gs4/pickle/
    backside: False
    aug_seq: False
    only_front: False
            
  sacson:
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_sacson/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_sacson/test/
    image: /nfs/kun2/datasets/lelan/dataset_LeLaN_sacson/
    pickle: /nfs/kun2/datasets/lelan/dataset_LeLaN_sacson/
    backside: False
    aug_seq: False
    only_front: False
            
  go_stanford2:
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_gs2/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_gs2/test/
    image: /nfs/kun2/datasets/lelan/dataset_LeLaN_gs2/
    pickle: /nfs/kun2/datasets/lelan/dataset_LeLaN_gs2/
    backside: False
    aug_seq: False
    only_front: False

  humanw:
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_humanw/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_humanw/test/
    image: /nfs/kun2/datasets/lelan/dataset_LeLaN_humanwalk/
    pickle: /nfs/kun2/datasets/lelan/dataset_LeLaN_humanwalk/    
    backside: False
    aug_seq: False 
    only_front: True   

  youtube:
    train: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_youtube/train/
    test: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/data_splits/lelan_youtube/test/
    image: /nfs/kun2/datasets/lelan/dataset_LeLaN_youtube/
    pickle: /nfs/kun2/datasets/lelan/dataset_LeLaN_youtube/        
    backside: False
    aug_seq: False 
    only_front: True  
# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 1000 #0 # in iterations

#print_log_freq: 10 # in iterations
#image_log_freq: 10 #0 # in iterations

num_images_log: 30 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.05
#eval_fraction: 0.9
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs

load_exaug: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/deployment/model_weights
load_nomad: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/deployment/model_weights
load_bdd: /home/noriaki/Learning-to-Drive-Anywhere-with-MBRA2/deployment/model_weights
#load_run: frodobot-gnm-lelan/frodobot-gnm_2025_04_09_23_01_49_shadow_bdd2
load_run: frodobot-gnm-lelan/frodobot-gnm_2025_05_30_16_54_40
